### ISSUE TITLE
How about proto file changes?

### ISSUE THREAD

**Issue by mychina75** [yonghenglh6/DepthwiseConvolution#3]
Dear Liu,
Thank you for your work.

I can not find changes in caffe.proto file. Can you provide this too?
there are compile issues when use the codes. multiple variables do not defined. I am not sure if missed some define in .h file...

And, I found comments in the codes, this is only for stride 1?

**Comment by yonghenglh6** [comment]
It is for all strides. you may test it by the check.py in test folder.
The caffe.proto file is not altered because no new or additional parameter is needed compared with convolution param. So, I just use original conv_param instead of creating a new depthwise_conv_param in caffe.proto, which leads to a easy way to convert the weights to caffe2's.
